### ISSUE TITLE
Error when reading emails in windows live mail.

### ISSUE THREAD

**Issue by nvdaTrac** [nvaccess/test_nvdaTracImport#166]
**Reported by cornelius on 6 May 2008 03:04 UTC**
When reading Mails in Windows Live mail, NVDA sometimes generate errors.

ERROR - queueHandler.flushQueue:
Error in func processFocusWinEvents from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 52, in flushQueue
  File "IAccessibleHandler.pyc", line 852, in processFocusWinEvents
  File "IAccessibleHandler.pyc", line 773, in focus_winEventCallback
  File "IAccessibleHandler.pyc", line 843, in focus_manageEvent
  File "api.pyc", line 104, in setFocusObject
  File "virtualBufferHandler.pyc", line 61, in update
  File "virtualBuffers_old\MSHTML.pyc", line 76, in __init__
  File "virtualBuffers_old\MSHTML.pyc", line 150, in loadDocument
  File "virtualBuffers_old\MSHTML.pyc", line 339, in fillBuffer
  File "virtualBuffers_old\MSHTML.pyc", line 222, in fillBuffer
  File "virtualBuffers_old\MSHTML.pyc", line 344, in getDomNodeID
  File "comtypes\client\dynamic.pyc", line 80, in __getattr__
  File "comtypes\automation.pyc", line 550, in GetIDsOfNames
COMError: (-2147024891, 'Access is denied.', (None, None, None, 0, None))

**Comment by nvdaTrac** [comment]
**Comment by jteh on 30 May 2008 01:10 UTC**
Do these errors actually affect functionality or do they just generate annoying error sounds and log entries?

**Comment by nvdaTrac** [comment]
**Modified by jteh on 5 Dec 2008 02:42 UTC**

**Comment by nvdaTrac** [comment]
**Comment by mdcurran on 14 Apr 2009 00:33 UTC**
The code causing this error no longer exists. If the error still occures with latest NVDA snapshots please reopen and include a new log error. From a quick test I have done, the error seems to be gone.
