### ISSUE TITLE
Critical bug in Microsoft Word 2003

### ISSUE THREAD

**Issue by nvdaTrac** [nvaccess/test_nvdaTracImport#196]
**Reported by swigjr23 on 18 Jun 2008 23:50 UTC**
When entering word 2003.  This error persists every time you hit the arrow keys.  It even happens when you lode word it say microsoft word then the sound.  The exception follows.
version 2146 running from sources

```
ERROR - queueHandler.flushQueue:
Error in func _queueEventCallback from eventQueue
Traceback (most recent call last):
  File "C:\source\source\queueHandler.py", line 52, in flushQueue
    func(*args,**kwargs)
  File "C:\source\source\eventHandler.py", line 40, in _queueEventCallback
    executeEvent(eventName,obj)
  File "C:\source\source\eventHandler.py", line 73, in executeEvent
    executeEvent_appModuleLevel(eventName,obj)
  File "C:\source\source\eventHandler.py", line 112, in executeEvent_appModuleLevel
    executeEvent_defaultAppModuleLevel(name,obj)
  File "C:\source\source\eventHandler.py", line 119, in executeEvent_defaultAppModuleLevel
    executeEvent_virtualBufferLevel(name,obj)
  File "C:\source\source\eventHandler.py", line 126, in executeEvent_virtualBufferLevel
    executeEvent_NVDAObjectLevel(name,obj)
  File "C:\source\source\eventHandler.py", line 130, in executeEvent_NVDAObjectLevel
    getattr(obj,'event_%s'%name)()
  File "C:\nvda\source\NVDAObjects\IAccessible\__init__.py", line 692, in event_gainFocus
    Window.event_gainFocus(self)
  File "C:\nvda\source\NVDAObjects\__init__.py", line 632, in event_gainFocus
    api.setNavigatorObject(self)
  File "C:\source\source\api.py", line 168, in setNavigatorObject
    globalVars.reviewPosition=obj.makeTextInfo(textHandler.POSITION_CARET)
  File "C:\nvda\source\NVDAObjects\__init__.py", line 682, in makeTextInfo
    return self.TextInfo(self,position)
  File "C:\nvda\source\NVDAObjects\IAccessible\winword.py", line 92, in __init__
    self._rangeObj.Collapse()
  File "C:\Python25\Lib\site-packages\win32com\client\dynamic.py", line 467, in __getattr__
    if self._olerepr_.mapFuncs.has_key(attr): return self._make_method_(attr)
  File "C:\Python25\Lib\site-packages\win32com\client\dynamic.py", line 295, in _make_method_
    methodCodeList = self._olerepr_.MakeFuncMethod(self._olerepr_.mapFuncs[name], methodName,0)
  File "C:\Python25\Lib\site-packages\win32com\client\build.py", line 297, in MakeFuncMethod
    return self.MakeDispatchFuncMethod(entry, name, bMakeClass)
  File "C:\Python25\Lib\site-packages\win32com\client\build.py", line 318, in MakeDispatchFuncMethod
    s = linePrefix + 'def ' + name + '(self' + BuildCallList(fdesc, names, defNamedOptArg, defNamedNotOptArg, defUnnamedArg, defOutArg) + '):'
  File "C:\Python25\Lib\site-packages\win32com\client\build.py", line 604, in BuildCallList
    argName = MakePublicAttributeName(argName)
  File "C:\Python25\Lib\site-packages\win32com\client\build.py", line 542, in MakePublicAttributeName
    return filter( lambda char: char in valid_identifier_chars, className)
  File "C:\Python25\Lib\site-packages\win32com\client\build.py", line 542, in <lambda>
    return filter( lambda char: char in valid_identifier_chars, className)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x83 in position 52: ordinal not in range(128)
```

I am running windows xp media center edition.

**Comment by nvdaTrac** [comment]
**Comment by mdcurran on 19 Jun 2008 00:36 UTC**
*Have any service packs or updates been applied to MS Office 2003?
*Is this an english copy of MS Word / MS Office, or another language?
*Since running from source, What version of Python Windows Extentions (Pywin32) is installed? Note I personally havn't tried 211 yet.
*If using Pywin32 version 211, try 210 and see if the problem is fixed.

**Comment by nvdaTrac** [comment]
**Comment by swigjr23 on 20 Jun 2008 01:20 UTC**
I haven't instaled any service packs.  I am running the english version.  I think I am running the latest windows extentions; I will try and down grade and get back to you.

**Comment by nvdaTrac** [comment]
**Comment by swigjr23 on 20 Jun 2008 02:28 UTC**
I was able to get the windows extentions 210, and the problem was fixed.  Thanks for the help.

**Comment by nvdaTrac** [comment]
**Comment by jteh on 20 Aug 2008 13:20 UTC**
reporter: Can you please test this with pywin32 build 212 and report whether the problem persists?

**Comment by nvdaTrac** [comment]
**Comment by swigjr23 on 20 Aug 2008 18:48 UTC**
It works fine with the latest version 212.  I think it is fixed.
