### ISSUE TITLE
Open Office mouse and sound error

### ISSUE THREAD

**Issue by nvdaTrac** [nvaccess/test_nvdaTracImport#265]
**Reported by hurrikenny on 27 Sep 2008 21:32 UTC**
When typing in Open Office 2.4 the letters come up ok, but if the mouse gets moved it creates an error sound. It doesn't matter in what direction, and the longer the move of the mouse the more constant the error sound. This is the error log I copied so people can see what it says.

```
ERROR - mouseHandler.executeMouseMoveEvent (17:33:44):
api.notifyMouseMoved
Traceback (most recent call last):
  File "mouseHandler.pyc", line 126, in executeMouseMoveEvent
  File "NVDAObjects\JAB\__init__.pyc", line 333, in event_mouseMove
  File "NVDAObjects\__init__.pyc", line 700, in makeTextInfo
  File "NVDAObjects\__init__.pyc", line 164, in __init__
NotImplementedError: position: <textHandler.Bookmark object at 0x020E2E30> not supported
```

**Comment by nvdaTrac** [comment]
**Modified by hurrikenny on 27 Sep 2008 21:33 UTC**

**Comment by nvdaTrac** [comment]
**Modified by hurrikenny on 8 Oct 2008 04:37 UTC**

**Comment by nvdaTrac** [comment]
**Comment by jteh on 9 Oct 2008 03:01 UTC**
Is this fixed by r2419?

**Comment by nvdaTrac** [comment]
**Comment by aleksey_s on 26 Nov 2008 08:55 UTC**
i think this can be closed as no further comments from reporter a long of time.
